server:
  port: ${APP_PORT:8090}
spring:
  application:
    name: code-me-app
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5440/code_me}
    username: ${DB_USER:code_me}
    password: ${DB_PASSWORD:1235}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
