name: Trigger auto deployment for algo-arena

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/algo-arena-AutoDeployTrigger-d88a69fb-1292-4a15-99c0-71701f4d9756.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ALGOARENA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ALGOARENA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ALGOARENA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.ALGOARENA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ALGOARENA_REGISTRY_PASSWORD }}
          containerAppName: algo-arena
          resourceGroup: a1
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


